jQuery(function($){$('.commentlist > li:last-child').addClass('last');$('#nav li:last-child').addClass('last');$('#nav > ul > li.has_dropdown').hover(function(){$(this).addClass('hover');$(this).find('.dropdown:eq(0)').show();},function(){$(this).removeClass('hover');$(this).find('.dropdown:eq(0)').hide();});$('#nav ul li.has_dropdown ul li').hover(function(){$(this).find('.dropdown:eq(0)').show();},function(){$(this).find('.dropdown:eq(0)').hide();});var logo_offset=$('#logo').offset().top;var last_nav_elem_offset=$('#nav > ul > li:last').offset().top;var nav_padding=parseInt($('#nav').css('margin-top').replace('px'));while(last_nav_elem_offset-nav_padding!=logo_offset&&$('#nav li').length>1){$('#nav > ul > li:last').remove();last_nav_elem_offset=$('#nav > ul > li:last').offset().top}
var target=$("#topComps");if(target){var container={};$('table.metaInfo tr.data').each(function(index){var link=$(this).children().eq(0).html();var type=$(this).children().eq(1).text();var distance=$(this).children().eq(2).text();var time=$(this).children().eq(3).text();var fixedTime=getFixedTime(time);if(container[type+distance]==null){var obj={type:type,distance:distance,time:fixedTime,link:link,rawTime:time};container[type+distance]=obj;}else if(container[type+distance].time>fixedTime){container[type+distance]={type:type,distance:distance,time:fixedTime,link:link,rawTime:time};}});var html="";html+="<table class='metaInfo bestOf'>";html+="<tr><th colspan='4'>Melhores Tempos</th></tr>"
for(var name in container){html+="<tr class='data'>";html+="<td class='headline'>"+container[name].link+"</td>";html+="<td>"+container[name].type+"</td>";html+="<td>"+container[name].distance+"</td>";html+="<td>"+container[name].rawTime+"</td>";html+="</tr>";}
html+="</table>";target.html(html);}
$(document).ready(function(){slideShow(4000);});});function slideShow(speed){$('ul.slideshow').append('<li id="slideshow-caption" class="caption"><div class="slideshow-caption-container"><h3></h3><p></p></div></li>');$('ul.slideshow li').css({opacity:0.0});$('ul.slideshow li:first').css({opacity:1.0});$('#slideshow-caption h3').html($('ul.slideshow a:first').find('img').attr('title'));$('#slideshow-caption p').html($('ul.slideshow a:first').find('img').attr('alt'));$('#slideshow-caption').css({opacity:0.7,bottom:0});var timer=setInterval('gallery()',speed);$('ul.slideshow').hover(function(){clearInterval(timer);},function(){timer=setInterval('gallery()',speed);});}
function gallery(){var current=($('ul.slideshow li.show')?$('ul.slideshow li.show'):$('#ul.slideshow li:first'));var next=((current.next().length)?((current.next().attr('id')=='slideshow-caption')?$('ul.slideshow li:first'):current.next()):$('ul.slideshow li:first'));var title=next.find('img').attr('title');var desc=next.find('img').attr('alt');next.css({opacity:0.0}).addClass('show').animate({opacity:1.0},1000);$('#slideshow-caption').slideToggle(300,function(){$('#slideshow-caption h3').html(title);$('#slideshow-caption p').html(desc);$('#slideshow-caption').slideToggle(500);});current.animate({opacity:0.0},1000).removeClass('show');}
function getFixedTime(raw)
{raw=raw.replace(/ /i,"");var total=0;var idx=raw.indexOf("h");if(idx>=0){total+=parseInt(raw.substring(0,idx))*60*60;raw=raw.substring(idx+1);}
idx=raw.indexOf("m");if(idx>=0){total+=parseInt(raw.substring(0,idx))*60;raw=raw.substring(idx+1);}
idx=raw.indexOf("s");if(idx>=0){total+=parseInt(raw.substring(0,idx));}
return total;}
